repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

# Lint: Dockerfile
- repo: https://github.com/hadolint/hadolint.git
  rev: v2.12.0
  hooks:
    - id: hadolint-docker
