name: Cleanup
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: cleanup old versions
        uses: "actions/delete-package-versions@v5"
        with:
          owner: 'cschritt'
          package-name: 'nym-mixnode'
          package-type: 'container'
          delete-only-untagged-versions: true
          min-versions-to-keep: 10
