name: Release

on:
  push:
    # Publish semver tags as releases.
    tags: [ '*' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  pull-requests: read
  issues: read

jobs:
  changelog:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: "actions/checkout@v4"

      - name: generate changelog
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: false
